var razas_perro = 
[ "Otro",
"Affenpinscher",
"Airedale terrier",
"Akita Inu",
"Akita Americano",
"Alano español",
"Alaskan malamute",
"American Hairless terrier",
"American Staffordshire Terrier",
"Antiguo Perro Pastor Inglés",
"Boyero de Appenzell|Appenzeller",
"Pastor ganadero australiano|Australian Cattle Dog",
"Australian Silky Terrier",
"Azawakh",
"Perro majorero|Bardino (Perro majorero)",
"Basenji",
"Basset hound",
"Beagle",
"Beauceron",
"Bichon frisé",
"Bichón maltés",
"Bobtail",
"Perro de San Huberto|Bloodhound",
"Border collie",
"Borzoi",
"Boston terrier",
"Bóxer",
"Braco alemán de pelo corto",
"Braco alemán de pelo duro",
"Braco de Auvernia",
"Braco francés",
"Braco húngaro",
"Braco italiano",
"Braco tirolés",
"Braco de Saint Germain",
"Braco de Weimar",
"Bull Terrier",
"Bulldog americano",
"Bulldog francés",
"Bulldog inglés",
"Bullmastiff",
"Can de palleiro",
"Caniche",
"Cão da Serra da Estrela",
"Cão da Serra de Aires",
"Cão de Agua Português",
"Cão de Castro Laboreiro",
"Cão de Fila de São Miguel",
"Cavalier King Charles Spaniel",
"Retriever de Chesapeake|Chesapeake Bay Retriever",
"Chihuahueño (perro)|Chihuahueño ",
"Crestado Chino",
"Cimarrón Uruguayo",
"Chow chow",
"Clumber spaniel ",
"Cocker spaniel americano",
"Cocker spaniel inglés",
"Collie",
"Collie barbudo|Bearded collie",
"Dachshund",
"Dálmata (perro)|Dálmata",
"Dandie Dinmont Terrier",
"Deerhound",
"Dobermann",
"Dogo alemán",
"Dogo argentino",
"Dogo de burdeos",
"Dogo del Tíbet",
"Dogo guatemalteco",
"Springer Spaniel Inglés|English springer spaniel",
"Boyero de Entlebuch|Entlebucher",
"Spaniel Bretón|Épagneul bretón",
"Spaniel francés|Épagneul français",
"Epagneul papillón",
"Eurasier",
"Fila Brasileiro",
"Flat-Coated Retriever",
"Fox Terrier",
"Galgo español",
"Galgo húngaro",
"Galgo inglés",
"Galgo italiano",
"Golden retriever",
"Gran danés",
"Gegar colombiano",
"Greyhound",
"Grifón belga",
"Hovawart",
"Husky siberiano",
"Jack Russell Terrier",
"Keeshond",
"Kerry blue terrier",
"Komondor",
"Kuvasz ",
"Labrador retriever|Labrador",
"Lakeland Terrier",
"Pastor belga laekenois|Laekenois",
"Landseer",
"Lebrel afgano",
"Leonberger",
"Wolfdog|Perro lobo de Saarloos",
"Lhasa apso",
"Pequeño_perro_león|Löwchen",
"Maltés (perro)|Maltés",
"Malinois",
"Manchester terrier",
"Mastín afgano",
"Mastín del Pirineo",
"Mastín español",
"Mastín inglés",
"Mastín napolitano",
"Mastín tibetano",
"Mucuchies",
"Mudi",
"Nova Scotia Duck Tolling Retriever",
"Ovejero magallánico",
"Pastor alemán",
"Pastor belga",
"Pastor blanco suizo",
"Pastor catalán",
"Pastor Croata|Pastor croata",
"Pastor garafiano",
"Pastor holandés",
"Pastor Chiribaya|Pastor peruano Chiribaya",
"Pastor de los Pirineos",
"Pastor leonés",
"Perro de pastor mallorquín|Pastor mallorquín",
"Pastor de Maremma|Pastor maremmano-abrucés",
"Pastor vasco",
"Pekinés (raza de perro)|Pekinés",
"Pembroke Welsh Corgi",
"Pequeño Lebrel Italiano",
"Pointer inglés|Perdiguero francés",
"Perdiguero portugués",
"Perro cimarrón uruguayo",
"Perro de agua americano",
"Perro de agua español",
"Perro de agua irlandés",
"Perro de agua portugués",
"Perro dogo mallorquín",
"Perro esquimal canadiense",
"Perro_de_montaña_de_los_Pirineos|Perro de Montaña de los Pirineos",
"Perro Fino Colombiano|Perro fino colombiano",
"Perro pastor de las islas Shetland",
"Perro sin pelo del Perú|Perro peruano sin pelo",
"Phalène",
"Pinscher alemán ",
"Pinscher miniatura",
"Pitbull",
"Podenco canario",
"Podenco ibicenco",
"Podenco portugués",
"Pointer inglés|Pointer",
"Pomerania (perro)|Pomerania",
"Presa canario",
"Pudelpointer",
"Pug",
"Puli (perro)|Puli",
"Pumi (perro)|Pumi",
"Rafeiro do Alentejo",
"Ratonero bodeguero andaluz",
"Ratonero mallorquín",
"Ratonero valenciano",
"Rhodesian Ridgeback",
"Rottweiler",
"Saluki",
"Samoyedo",
"San Bernardo (perro)|San Bernardo",
"Schnauzer estándar",
"Schnauzer gigante",
"Schnauzer miniatura",
"Staffordshire Bull Terrier",
"Setter inglés",
"Setter irlandés",
"Shar Pei",
"Shiba Inu",
"Shih Tzu",
"Siberian husky",
"Skye terrier",
"Spitz (perro)|Spitz enano",
"Spitz (perro)|Spitz grande",
"Spitz (perro)|Spitz mediano",
"Spitz japonés",
"Sussex spaniel",
"Teckel",
"Terranova (perro)|Terranova",
"Terrier alemán",
"Terrier australiano",
"Terrier brasileño",
"Terrier chileno",
"Terrier escocés",
"Terrier galés",
"Terrier irlandés",
"Terrier ruso negro",
"Terrier tibetano",
"Pastor_belga_tervuerense|Tervueren",
"Weimaraner",
"West Highland White Terrier",
"Whippet",
"Keeshond|Wolfsspitz",
"Xoloitzcuintle",
"Yorkshire terrier"];

var razas_gatos = 
[ "Otro",
"Abisinio (gato)|Abisinio",
"Aphrodite's Giants",
"Australian Mist",
"Curl Americano|American Curl",
"Azul ruso",
"American shorthair",
"American wirehair",
"Angora turco",
"Felis silvestris lybica|Africano doméstico",
"Bengala (animal)|Bengala",
"Bobtail japonés",
"Bombay (gato)|Bombay",
"Bosque de Noruega",
"Brazilian Shorthair",
"Brivon de pelo corto",
"Brivon de pelo largo",
"British Shorthair",
"Burmés",
"Burmilla",
"Cornish rex",
"California Spangled",
"Ceylon",
"Cymric",
"Chartreux",
"Deutsch Langhaar",
"Devon rex",
"Profelis aurata|Dorado africano",
"Don Sphynx",
"Dragon Li",
"Gato común europeo|Europeo Común",
"Gato exótico|Exótico de Pelo Corto",
"Gato europeo bicolor",
"Gato FoldEx|FoldEx",
"German Rex",
"Habana brown ",
"Gato himalayo|Himalayo",
"Korat",
"Khao Manee",
"Maine Coon",
"Gato Manx|Manx ",
"Mau egipcio",
"Munchkin (gato)|Munchkin",
"Ocicat",
"Gato oriental|Oriental ",
"Gato oriental de pelo largo|Oriental de pelo largo",
"Ojos azules",
"Gato PerFold|PerFold",
"Gato Persa|Persa Americano o Moderno",
"Traditional Persian|Persa Clásico o Tradicional",
"Peterbald",
"Pixie Bob",
"Ragdoll",
"Sagrado de Birmania ",
"Scottish Fold ",
"Selkirk rex ",
"Gato Serengeti|Serengeti ",
"Gato seychellois|Seychellois ",
"Gato siamés|Siamés ",
"Siamés moderno|Siamés Moderno ",
"Siamés tradicional|Siamés Tradicional ",
"Siberiano (gato)|Siberiano ",
"Snowshoe ",
"Sphynx",
"Gato Tonkinés|Tonkinés ",
"Gato Van Turco|Van Turco"]